### PR TITLE
a guess at adding the host midi port to the UI

### PR DESCRIPTION
**Pull request by ssj71**
Hi falktx:

I tried to implement the mod-host:midi_in port in the UI, but I can't figure out how to test since the files install to a read-only part of the mod's file system. So I'll just do this PR and you can either tell me how to test or just check it yourself. :)

This adds some cool possibilities like manipulating midi learn to have 1 knob on your midi controller change several parameters on the pedalboard, or having a pedal generate automation (like a midi lfo). Hopefully this can be a useful contribution.

### CODE REVIEW

**Comment by falkTX** [comment]
You can mount as RW like this:
`mount / -o remount,rw`

I use this script to do a full deploy of a custom mod-ui:
```
#!/bin/bash

set -e

BASEDIR=/home/falktx/FOSS/GIT-mine/MOD/mod-app/source/modules/mod-ui
TARGET=root@modduo.local

cd $BASEDIR

ssh $TARGET rm -rf /usr/share/mod/html/
ssh $TARGET rm -f /usr/lib/python3.4/site-packages/mod/*.py*
ssh $TARGET rm -f /usr/lib/python3.4/site-packages/mod/communication/*.py*

scp -r $BASEDIR/html                $TARGET:/usr/share/mod/
scp $BASEDIR/mod/*.py               $TARGET:/usr/lib/python3.4/site-packages/mod/
scp $BASEDIR/mod/communication/*.py $TARGET:/usr/lib/python3.4/site-packages/mod/communication/
scp $BASEDIR/screenshot.js          $TARGET:/usr/share/mod/

ssh $TARGET rm -rf /usr/lib/python3.4/site-packages/mod/__pycache__
ssh $TARGET rm -rf /usr/lib/python3.4/site-packages/mod/communication/__pycache__

echo "all ok"
```

**Comment by falkTX** [comment]
You might want to add your ssh public key to the authorized_keys inside the mod so you don't need a password everytime.

**Comment by falkTX** [comment]
Oh, and after the initial first copy, you can use this script which only modifies main code and leaves artwork, resources, etc intact (for faster deploy).

```
#!/bin/bash

set -e

BASEDIR=/home/falktx/FOSS/GIT-mine/MOD/mod-app/source/modules/mod-ui
TARGET=root@192.168.51.1

cd $BASEDIR

scp  $BASEDIR/html/css/*.css        $TARGET:/usr/share/mod/html/css/
scp  $BASEDIR/html/*.html           $TARGET:/usr/share/mod/html/
scp  $BASEDIR/html/js/*.js          $TARGET:/usr/share/mod/html/js/
scp  $BASEDIR/mod/*.py               $TARGET:/usr/lib/python3.4/site-packages/mod/
scp  $BASEDIR/mod/communication/*.py $TARGET:/usr/lib/python3.4/site-packages/mod/communication/

ssh  $TARGET rm -rf /usr/lib/python3.4/site-packages/mod/__pycache__
ssh  $TARGET rm -rf /usr/lib/python3.4/site-packages/mod/communication/__pycache__

echo "all ok"
```

Don't forget to run:
```
systemctl stop mod-ui
mod-ui.run
```
To run mod-ui inside the local shell, so you have access to its stdout and stderr output.

**Comment by ssj71** [comment]
haha, well, I wasn't even close, I'll have to dig some more to figure out how this really works. Thanks for all the pointers!

**Comment by unbracketed** [comment]
For the initial connection, the password is `mod` as noted [here](https://forum.moddevices.com/t/modduo-configure-via-terminal/76/8)

**Comment by falkTX** [comment]
MIDI loopback has been added (needs up to date midi-merger and mod-host)
Feature is coming to v1.11, I am closing this PR since the new implementation supersedes it.

**Pull request closed without merging**
