### PR TITLE
Re-enable MIDI program change switching after last web session is closed

### PR DESCRIPTION
**Pull request by tristantarrant**
When a web session is started, MIDI program change is disabled. However it is not re-enabled after the last web session is closed.

Also renamed a method with a typo :)

### CODE REVIEW

**Comment by falkTX** [comment]
This is already handled as part of `initialize_hmi` so at least it needs a check for HMI not being present.

**Comment by tristantarrant** [comment]
So wrap it in 
```python
if self.hmi.isFake() 
```
?

**Comment by falkTX** [comment]
Please put it inside the `if not hmi.initialized` block, with a comment saying something like "typically `initialize_hmi` takes care of this but without HMI we need to do it manually"

Then confirm if that works for you of course.

**Comment by tristantarrant** [comment]
Hey @falkTX , apologies for not following up on this earlier. I've made the changes you asked for

**Comment by falkTX** [comment]
ok 1 more small request, sorry.
instead of doing the midi program monitor message later, have the current call wait for it to finish.
like so:

```
if midi_pb_prgch >= 1 and midi_pb_prgch <= 16:
    self.send_notmodified("monitor_midi_program %d 1" % (midi_pb_prgch-1), callback)
else:
    callback(True)
```

if this works for you, then should be all good.

**Comment by falkTX** [comment]
Merged as 7f70c63e99b5d6bd4303295ed189ee1746e9de6c thanks

**Pull request closed without merging**
