### PR TITLE
Finish tempo divider implementation

### PR DESCRIPTION
**Pull request by blushi**
Tempo sync can now be enabled for ports with `lv2:portProperty  mod:tempoRelatedDynamicScalePoints;`

### CODE REVIEW

**Comment by falkTX** [comment]
Just tested this PR, not for the new code but to check for regressions. (waiting for a valid plugin that has special tempo params)

Something is off with the addressing page.
While we see the pink highlight on the settings screen items, indicating which controls are addressed, opening the addressing page we see everything being white instead of the grey/disabled color.
No error gets logged in the browser console or mod-ui process.

**Comment by falkTX** [comment]
Now got my hands in a few plugins that implement the behaviour this PR targets, and I can see some issues there too.
1. checkbox for translating to musical tempo appears initially, but then disappears when clicking on MIDI (which is expected) but then it never appears back again. this checkbox should only be visible when addressing is for "Device". under "None" it should not appear
2. there is a combo-box with a list of values, which ends up being the same as the values used in hmi. not sure what the purpose of this is, but is very confusing and perhaps useless.
3. when a musical-tempo parameter is addressed and that checkbox is on, I can see the possible values as a list in hmi, but changing these values does not change much on the web ui. it seems as if most of the values in the hmi list trigger no change at all

**Comment by blushi** [comment]
> Just tested this PR, not for the new code but to check for regressions. (waiting for a valid plugin that has special tempo params)
> 
> Something is off with the addressing page.
> While we see the pink highlight on the settings screen items, indicating which controls are addressed, opening the addressing page we see everything being white instead of the grey/disabled color.
> No error gets logged in the browser console or mod-ui process.

@falkTX What do you mean "everything being white"? Are you talking about the actuators per page table?

**Comment by falkTX** [comment]
> Are you talking about the actuators per page table?

Yes, it appears as if nothing is addressed when the table is shown

**Comment by blushi** [comment]
> > Are you talking about the actuators per page table?
> 
> Yes, it appears as if nothing is addressed when the table is shown

I can't reproduce it. Could you share the pedalboard you're using?

**Comment by blushi** [comment]
> Now got my hands in a few plugins that implement the behaviour this PR targets, and I can see some issues there too.
> 
> 1. checkbox for translating to musical tempo appears initially, but then disappears when clicking on MIDI (which is expected) but then it never appears back again. this checkbox should only be visible when addressing is for "Device". under "None" it should not appear

Just pushed a new commit to fix this. But from the specifications I got from @jesseverhage (quite a long time ago now), you should also be able to sync a param to tempo without actually mapping anything to the HMI, which would allow the tempo checkbox to appear above "None". Implementation-wise, I've created a "virtual" `/bpm` actuator. From a user point of view, I understand though that this might not be obvious. Any suggestions are welcome. 

> 2. there is a combo-box with a list of values, which ends up being the same as the values used in hmi. not sure what the purpose of this is, but is very confusing and perhaps useless.

It's used to set the initial divider value and is actually useful in the case of the virtual bpm addressing described above.

> 3. when a musical-tempo parameter is addressed and that checkbox is on, I can see the possible values as a list in hmi, but changing these values does not change much on the web ui. it seems as if most of the values in the hmi list trigger no change at all

I believe it's because the min/max values are not set properly and in this particular case, the hmi always send the same value when going through the list. Could you confirm?

**Comment by falkTX** [comment]
> I can't reproduce it. Could you share the pedalboard you're using?

All the pedalboards I have tried have this issue.
So loading any remote pedalboard from pedalboards.moddevices.com will trigger it. Like this one http://integrate.moddevices.com/5d58752e2564d46f59dbde22

I can see hmi having some addressings on the screen, but the table is empty.
Screenshot_20190829_092252

**Comment by falkTX** [comment]
> I believe it's because the min/max values are not set properly and in this particular case, the hmi always send the same value when going through the list. Could you confirm?

Just checked, when doing the addressing, this is the message sent:
```
a 1 "TIME" 12 "ms" 4.000000 500.000000 41.667000 33 11 "1/4" 4.000000 "1/4." 6.000000 "1/8T" 5.333000 "1/8" 8.000000 "1/8." 12.000000 "1/16T" 10.666000 "1/16" 16.000000 "1/16." 24.000000 "1/32T" 21.333000 "1/32" 32.000000 "1/32." 48.000000
```
scrolling through the values, hmi sends only `41.667000` or `48.0`.
that confirms what you say about the min/max not being correct, as the addressing is using `41.667000` as min and `500.0` as max.
hmi does not handle this well, but we are not sending correct data to it anyway either.

**Comment by blushi** [comment]
> 
> All the pedalboards I have tried have this issue.
> So loading any remote pedalboard from pedalboards.moddevices.com will trigger it. Like this one http://integrate.moddevices.com/5d58752e2564d46f59dbde22
> 
> I can see hmi having some addressings on the screen, but the table is empty.

Latest commit should fix this.

**Comment by falkTX** [comment]
I am merging this to master, since it is a desired feature.
If something is still broken, we will have to fix it :)

**Pull request merged**
